language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.1

    # The SDK version used to compile your project
    - android-25
    
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
- chmod +x gradlew

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - android update sdk --no-ui --filter build-tools-25.0.1,android-25,platform-tools,tools,extra-android-support,extra-android-m2repository,extra-google-m2repository

before_script:
- ./gradlew -q app:dependencies
