language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19
    
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19

before_install:
- chmod +x gradlew

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - android update sdk --no-ui --filter build-tools-19.1.0,android-19,platform-tools,tools,extra-android-support,extra-android-m2repository,extra-google-m2repository

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

before_deploy:
  - cp ./app/build/outputs/apk/*.apk .
  - ls ./app/build/outputs/apk/

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: "daed2a2b78ac597629277ac54bfbb7417f947a81"
    file: "app-release-unsigned.apk"
    on:
      repo: Osirys25/MaciejApp
      tags: true  
