language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-26
    
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-26
  target:
    - android-26
    
before_install:
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - android update sdk --no-ui --filter build-tools-26.0.1,android-26,platform-tools,tools,extra-android-support,extra-android-m2repository,extra-google-m2repository

before_script:
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

before_deploy:
  - cp ./app/build/outputs/apk/*.apk .
  - ls ./app/build/outputs/apk/

deploy:
  - provider: releases
    skip_cleanup: true
    api_key: "daed2a2b78ac597629277ac54bfbb7417f947a81"
    file: "app-debug.apk"
    on:
      repo: Osirys25/MaciejApp
      tags: true  
